### ISSUE TITLE
Placeholder: SilverStripe 4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [unclecheese/silverstripe-gridfield-betterbuttons#152]
This is a placeholder issue for tracking progress towards SS4 compatibility

## Requirements

- [x] Branch current master off for ongoing support of current version
- [x] Update composer constraints and branch alias: #150 
- [x] Rename code structure in preparation for namespacing and PSR-4: #150 
- [x] PSR-2 style compatibility, one class per file, etc: #151 
- [ ] Add namespace and implement throughout code
- [ ] Rename templates if required
- [ ] Add a few unit tests
- [ ] Update CMS button styles for Bootstrap 4
- [ ] Update documentation
